{% set version = "1.35.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-parallelly
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/parallelly_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/parallelly/parallelly_{{ version }}.tar.gz
  sha256: 3f5e9b6507196aab052c5e67f8b524b75aa356731c5eaffbadde76c967ad5dcd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  skip: True # [not linux64]]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base {{ r_version }}
  run:
    - r-base {{ r_version }}

test:
  commands:
    - $R -e "library('parallelly')"           # [not win]
    - "\"%R%\" -e \"library('parallelly')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/parallelly
  license: LGPL-2.1-or-later
  summary: Utility functions that enhance the 'parallel' package and support the built-in parallel backends of the 'future' package.  For example, availableCores() gives the number of CPU cores available to your R process as given by R options and environment variables, including those set by job schedulers on high-performance
    compute clusters. If none is set, it will fall back to parallel::detectCores(). Another example is makeClusterPSOCK(), which is backward compatible with parallel::makePSOCKcluster() while doing a better job in setting up remote cluster workers without the need for configuring the firewall to do port-forwarding to your
    local computer.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1

extra:
  recipe-maintainers:
    - conda-forge/r
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-furrr"
    recipe-maintainers:
      - bkreider


# Package: parallelly
# Version: 1.21.0
# Title: Enhancing the 'parallel' Package
# Imports: parallel, tools, utils
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Description: Utility functions that enhance the 'parallel' package and support the built-in parallel backends of the 'future' package.  For example, availableCores() gives the number of CPU cores available to your R process as given by R options and environment variables, including those set by job schedulers on high-performance compute clusters. If none is set, it will fall back to parallel::detectCores(). Another example is makeClusterPSOCK(), which is backward compatible with parallel::makePSOCKcluster() while doing a better job in setting up remote cluster workers without the need for configuring the firewall to do port-forwarding to your local computer.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# ByteCompile: TRUE
# URL: https://github.com/HenrikBengtsson/parallelly
# BugReports: https://github.com/HenrikBengtsson/parallelly/issues
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2020-10-26 23:32:18 UTC; hb
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Repository: CRAN
# Date/Publication: 2020-10-27 15:30:02 UTC
